### ISSUE TITLE
Quick start template Deploy RD Gateway into an existing VPC – domain-joined No longer working

### ISSUE THREAD

**Issue by badaldavda** [aws-quickstart/quickstart-microsoft-rdgateway#11]
When creating the stack I get an error when creating Launch Configuration -
AMI cannot be described (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: b678fcba-58b4-11e8-aa61-0560b123affb)

Looking internally I see the ami-838b53fc is de-registered.

Whereas looking for public ami for Windows_Server-2016-English-Full-Base-2018.04.11 I find the new ami - ami-3633b149 created on 8th of May 2018.

Can you please look at this issue and change the ami of the template?

**Comment by badaldavda** [comment]
On creating stack with ami-3633b149, it fails with failure signal -
2018-05-16 15:02:26,994 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2018-05-16 15:02:26,994 [DEBUG] Describing resource RDGWLaunchConfiguration in stack arn:aws:cloudformation:us-east-1:842865080923:stack/news122/7be72340-5919-11e8-b92e-500c21792a35
2018-05-16 15:02:27,447 [INFO] -----------------------Starting build-----------------------
2018-05-16 15:02:27,463 [DEBUG] Creating Scheduled Task for cfn-init resume
2018-05-16 15:02:27,480 [DEBUG] Scheduled Task created
2018-05-16 15:02:27,480 [INFO] Running configSets: config
2018-05-16 15:02:27,494 [INFO] Running configSet config
2018-05-16 15:02:27,494 [INFO] Running config setup
2018-05-16 15:02:27,494 [DEBUG] No packages specified
2018-05-16 15:02:27,510 [DEBUG] No groups specified
2018-05-16 15:02:27,510 [DEBUG] No users specified
2018-05-16 15:02:27,510 [DEBUG] No sources specified
2018-05-16 15:02:27,510 [DEBUG] Parent directory C:\cfn\modules does not exist, creating
2018-05-16 15:02:27,510 [DEBUG] Writing content to C:\cfn\modules\AWSQuickStart.zip
2018-05-16 15:02:27,510 [DEBUG] Retrieving contents from https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-rdgateway/submodules/quickstart-microsoft-utilities/modules/AWSQuickStart.zip
2018-05-16 15:02:27,510 [WARNING] Falling back to Signature Version 2 as no region was specified in S3 URL
2018-05-16 15:02:27,698 [DEBUG] No mode specified for C:\cfn\modules\AWSQuickStart.zip. The file will be created with the mode: 0664
2018-05-16 15:02:27,698 [WARNING] Unsupported OS for setting owner/group: nt
2018-05-16 15:02:27,698 [DEBUG] Parent directory C:\cfn\scripts does not exist, creating
2018-05-16 15:02:27,698 [DEBUG] Writing content to C:\cfn\scripts\Join-Domain.ps1
2018-05-16 15:02:27,698 [DEBUG] Retrieving contents from https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-rdgateway/submodules/quickstart-microsoft-utilities/scripts/Join-Domain.ps1
2018-05-16 15:02:27,698 [WARNING] Falling back to Signature Version 2 as no region was specified in S3 URL
2018-05-16 15:02:27,792 [DEBUG] No mode specified for C:\cfn\scripts\Join-Domain.ps1. The file will be created with the mode: 0664
2018-05-16 15:02:27,792 [WARNING] Unsupported OS for setting owner/group: nt
2018-05-16 15:02:27,792 [DEBUG] Writing content to C:\cfn\scripts\Unzip-Archive.ps1
2018-05-16 15:02:27,792 [DEBUG] Retrieving contents from https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-rdgateway/submodules/quickstart-microsoft-utilities/scripts/Unzip-Archive.ps1
2018-05-16 15:02:27,792 [WARNING] Falling back to Signature Version 2 as no region was specified in S3 URL
2018-05-16 15:02:27,885 [DEBUG] No mode specified for C:\cfn\scripts\Unzip-Archive.ps1. The file will be created with the mode: 0664
2018-05-16 15:02:27,885 [WARNING] Unsupported OS for setting owner/group: nt
2018-05-16 15:02:27,885 [DEBUG] Writing content to c:\cfn\cfn-hup.conf
2018-05-16 15:02:27,885 [DEBUG] No mode specified for c:\cfn\cfn-hup.conf. The file will be created with the mode: 0664
2018-05-16 15:02:27,885 [WARNING] Unsupported OS for setting owner/group: nt
2018-05-16 15:02:27,885 [DEBUG] Parent directory c:\cfn\hooks.d does not exist, creating
2018-05-16 15:02:27,885 [DEBUG] Writing content to c:\cfn\hooks.d\cfn-auto-reloader.conf
2018-05-16 15:02:27,901 [DEBUG] No mode specified for c:\cfn\hooks.d\cfn-auto-reloader.conf. The file will be created with the mode: 0664
2018-05-16 15:02:27,901 [WARNING] Unsupported OS for setting owner/group: nt
2018-05-16 15:02:27,901 [DEBUG] Writing content to c:\cfn\scripts\Initialize-RDGW.ps1
2018-05-16 15:02:27,901 [DEBUG] Retrieving contents from https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-rdgateway/scripts/Initialize-RDGW.ps1
2018-05-16 15:02:27,901 [WARNING] Falling back to Signature Version 2 as no region was specified in S3 URL
2018-05-16 15:02:27,980 [DEBUG] No mode specified for c:\cfn\scripts\Initialize-RDGW.ps1. The file will be created with the mode: 0664
2018-05-16 15:02:27,980 [WARNING] Unsupported OS for setting owner/group: nt
2018-05-16 15:02:27,980 [DEBUG] Writing content to c:\cfn\scripts\Set-EIP.ps1
2018-05-16 15:02:27,980 [DEBUG] Retrieving contents from https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-rdgateway/scripts/Set-EIP.ps1
2018-05-16 15:02:27,996 [WARNING] Falling back to Signature Version 2 as no region was specified in S3 URL
2018-05-16 15:02:28,073 [DEBUG] No mode specified for c:\cfn\scripts\Set-EIP.ps1. The file will be created with the mode: 0664
2018-05-16 15:02:28,073 [WARNING] Unsupported OS for setting owner/group: nt
2018-05-16 15:02:28,089 [DEBUG] Running command a-set-execution-policy
2018-05-16 15:02:28,089 [DEBUG] No test for command a-set-execution-policy
2018-05-16 15:02:28,668 [INFO] Command a-set-execution-policy succeeded
2018-05-16 15:02:28,668 [DEBUG] Command a-set-execution-policy output: 
2018-05-16 15:02:28,684 [DEBUG] Running command b-unpack-quickstart-module
2018-05-16 15:02:28,684 [DEBUG] No test for command b-unpack-quickstart-module
2018-05-16 15:02:29,293 [INFO] Command b-unpack-quickstart-module succeeded
2018-05-16 15:02:29,293 [DEBUG] Command b-unpack-quickstart-module output: 
GAC    Version        Location                                                                                         
---    -------        --------                                                                                         
True   v4.0.30319     C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression.FileSystem\v4.0_4.0.0.0__b77a...



2018-05-16 15:02:29,341 [DEBUG] Running command c-init-quickstart-module
2018-05-16 15:02:29,341 [DEBUG] No test for command c-init-quickstart-module
2018-05-16 15:02:30,013 [INFO] Command c-init-quickstart-module succeeded
2018-05-16 15:02:30,013 [DEBUG] Command c-init-quickstart-module output: 

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE


Name                           Property                                                                                
----                           --------                                                                                
AWSQuickStart                                                                                                          

Stack        : news122
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\AWSQuickStart\
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE
PSChildName  : AWSQuickStart
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry


Resource     : RDGWAutoScalingGroup
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\AWSQuickStart\
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE
PSChildName  : AWSQuickStart
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry


Region       : us-east-1
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\AWSQuickStart\
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE
PSChildName  : AWSQuickStart
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry


ErrorCount   : 0
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\AWSQuickStart\
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE
PSChildName  : AWSQuickStart
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry




2018-05-16 15:02:30,029 [DEBUG] Restarting cfn-hup due to change detected in dependency
2018-05-16 15:02:30,326 [INFO] Running config join
2018-05-16 15:02:30,326 [DEBUG] No packages specified
2018-05-16 15:02:30,326 [DEBUG] No groups specified
2018-05-16 15:02:30,326 [DEBUG] No users specified
2018-05-16 15:02:30,326 [DEBUG] No sources specified
2018-05-16 15:02:30,326 [DEBUG] No files specified
2018-05-16 15:02:30,358 [DEBUG] No services specified
2018-05-16 15:02:30,374 [DEBUG] Running command a-join-domain
2018-05-16 15:02:30,374 [DEBUG] No test for command a-join-domain
2018-05-16 15:02:32,000 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2018-05-16 15:02:32,000 [DEBUG] Signaling resource RDGWAutoScalingGroup in stack news122 with unique ID i-0840d2f478308d1a5 and status FAILURE
2018-05-16 15:02:32,625 [ERROR] Command a-join-domain (powershell.exe -Command "C:\cfn\scripts\Join-Domain.ps1 -DomainName 'badaldavda.tk' -UserName 'example\StackAdmin' -Password 'Password@123'") failed
2018-05-16 15:02:32,625 [DEBUG] Command a-join-domain output: Command failure in Add-Computer C:\cfn\scripts\Join-Domain.ps1 on line 19 
Exception: System.InvalidOperationException: Computer EC2AMAZ-RUT2ODM failed to join domain badaldavda.tk from its 
current workgroup WORKGROUP with following error message: The ...
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AWSQuickStart\AWSQuickStart.psm1:314 char:13
+             throw $CmdSafeErrorMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Command failure...essage: The ...:String) [], RuntimeException
    + FullyQualifiedErrorId : Command failure in Add-Computer C:\cfn\scripts\Join-Domain.ps1 on line 19 
    Exception: System.InvalidOperationException: Computer EC2AMAZ-RUT2ODM failed to join domain badaldavda.tk from its 
    current workgroup WORKGROUP with following error message: The ...
 

2018-05-16 15:02:32,625 [ERROR] Error encountered during build of join: Command a-join-domain failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command a-join-domain failed
2018-05-16 15:02:32,625 [ERROR] -----------------------BUILD FAILED!------------------------
2018-05-16 15:02:32,625 [ERROR] Unhandled exception during build: Command a-join-domain failed
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command a-join-domain failed

**Comment by nicolasd85** [comment]
I have the same problem
