### ISSUE TITLE
Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by yashah306** [aws-quickstart/quickstart-microsoft-rdgateway#18]
I am trying to deploy this CF template in my account. I am using existing VPC and passing on the parameters. However, I am getting an error saying "CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | RDGWAutoScalingGroup | Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement" Does anyone know about this? 
Any help would be appreciated.

**Comment by virtlima** [comment]
Can you specify what region you are running this in? Can you set the CloudFormation to [prevent rollback on failure](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-prevent-rollback-failure/). Once you so that can you check the errors within the Auto-Scaling Group, and also RDP to the instance if you can and take a look at C:\cfn\logs and to see if any of the scripts executed, if they didnt it will also have an error as to why they didnt.

**Comment by yashah306** [comment]
I am running this template in us-east-1. I RDP to the instance and checked the logs. I am getting this error. 
2019-06-07 19:02:19,525 [ERROR] ConnectionError
Traceback (most recent call last):
  File "cfnbootstrap\util.pyc", line 162, in _retry
  File "cfnbootstrap\util.pyc", line 234, in _timeout
ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
I checked instance settings, it is in public subnet and has internet connection.

**Comment by RandyBT** [comment]
Has anyone been able to resolve this? I am having the same issues and cannot figure it out =/

**Comment by nicolasd85** [comment]
I'm having the same issue:

![image](https://user-images.githubusercontent.com/54359525/64116711-6f0e9e80-cd69-11e9-9a51-894bb751c9c0.png)

I also don't see errors on Auto-Scaling Groups:
![image](https://user-images.githubusercontent.com/54359525/64117193-e7299400-cd6a-11e9-8c67-32db5f4c66bb.png)

Here is the log:

2019-09-02 13:00:22,032 [DEBUG] Restarting cfn-hup due to change detected in dependency
2019-09-02 13:00:22,313 [INFO] Running config join
2019-09-02 13:00:22,313 [DEBUG] No packages specified
2019-09-02 13:00:22,313 [DEBUG] No groups specified
2019-09-02 13:00:22,313 [DEBUG] No users specified
2019-09-02 13:00:22,313 [DEBUG] No sources specified
2019-09-02 13:00:22,313 [DEBUG] No files specified
2019-09-02 13:00:22,361 [DEBUG] No services specified
2019-09-02 13:00:22,375 [DEBUG] Running command a-join-domain
2019-09-02 13:00:22,375 [DEBUG] No test for command a-join-domain
2019-09-02 13:00:26,875 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2019-09-02 13:00:26,875 [DEBUG] Signaling resource RDGWAutoScalingGroup in stack RD-DOMAINGATEWAY with unique ID i-033f1c81dfd604b1b and status FAILURE
2019-09-02 13:00:27,438 [ERROR] Command a-join-domain (powershell.exe -Command "C:\cfn\scripts\Join-Domain.ps1 -DomainName '***********' -UserName 'DC\Admin' -Password '********") failed
2019-09-02 13:00:27,438 [DEBUG] Command a-join-domain output: Command failure in Add-Computer C:\cfn\scripts\Join-Domain.ps1 on line 19 
Exception: System.InvalidOperationException: Computer EC2AMAZ-FKAP2RT failed to join domain ************** from its 
current workgroup WORKGROUP with following error message: T...
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AWSQuickStart\AWSQuickStart.psm1:314 char:13
+             throw $CmdSafeErrorMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Command failure...r message: T...:String) [], RuntimeException
    + FullyQualifiedErrorId : Command failure in Add-Computer C:\cfn\scripts\Join-Domain.ps1 on line 19 
    Exception: System.InvalidOperationException: Computer EC2AMAZ-FKAP2RT failed to join domain dc.bairesdev.com from  
   its current workgroup WORKGROUP with following error message: T...
 

2019-09-02 13:00:27,438 [ERROR] Error encountered during build of join: Command a-join-domain failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command a-join-domain failed
2019-09-02 13:00:27,438 [ERROR] -----------------------BUILD FAILED!------------------------
2019-09-02 13:00:27,438 [ERROR] Unhandled exception during build: Command a-join-domain failed
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command a-join-domain failed

**Comment by nicolasd85** [comment]
I can ping the domain
![image](https://user-images.githubusercontent.com/54359525/64118562-43da7e00-cd6e-11e9-81a6-6df0cb551662.png)

**Comment by nicolasd85** [comment]
Sorry i realize how to solve it.
It seems that when you create the Domain with the scenario 1 template it ask for two passwords for the admin account.
The remote destkop gateway template doesn't work with the first password. You need to use the secondary password.

**Comment by virtlima** [comment]
@yashah306 and @RandyBT, Where you able to figure out the issue? Or are you still having this issue. I apologize for the delayed response on this issue

**Comment by carrollh** [comment]
I'm having the same problem, and have just been ignoring it for months. It's how the submodule urls are defined. Since I'm launching from a different quickstart I'm passing my rdgateway submodule path (test/submodules/quickstart-microsoft-rdgateway/) in for QSS3KeyPrefix. I have rdgateway as a submodule, but running 'git submodule update --init' does not recursively update submodules of submodules so that folder is empty when rdgw-domain.template tries to download AWSQuickStart.zip. If I instead just pass my base s3 folder (test/) for QSS3KeyPrefix it can find AWSQuickStart.zip (because I also have quickstart-microsoft-utilities as a submodule), but then it fails a few lines later when trying to download the Initialize-RDGW.ps1 file (because it's looking for it in my project's scripts folder instead of the quickstart-microsoft-rdgateway/scripts folder). It seems the only way to get it to work is to go into my test/submodules/quickstart-microsoft-rdgateway folder and run 'git submodule update --init' there and test/submodules/quickstart-microsoft-rdgateway/ in for QSS3KeyPrefix in my master template. I'm not sure if that is the intended way that is supposed to work, but I can't think of a better way at the moment.
